<?php
// $Id$

function services_oop_autoload_info() {
  return array(
    'ServicesOop' => array(
      'file' => 'includes/ServicesOop.inc',
    ),
    'RelationshipAnnotation' => array(
      'file' => 'includes/ServicesOop.inc',
    ),
    'AccessAnnotation' => array(
      'file' => 'includes/ServicesOop.inc',
    ),
    'ModelAnnotation' => array(
      'file' => 'includes/ServicesOop.inc',
    ),
    'ReflectionAnnotatedClass' => array(
      'file' => 'lib/annotations.php',
    ),
    'Annotation' => array(
      'file' => 'lib/annotations.php',
    ),
  );
}